name: pytest

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [ '3.9' ]
        torch: [ 'torch==1.10.0+cpu torchvision==0.11.1+cpu -f https://download.pytorch.org/whl/torch_stable.html' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install ${{ matrix.torch }}
          pip install -U pytest
      - name: run test
        run: |
          . venv/bin/activate
          pytest